// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheyWhoNameTheGods.Models;

namespace TheyWhoNameTheGods.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200808213919_AddingGodId")]
    partial class AddingGodId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TheyWhoNameTheGods.Models.Creation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BelongsToGod")
                        .HasColumnType("text");

                    b.Property<int>("GodId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Population")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.ToTable("Creations");
                });

            modelBuilder.Entity("TheyWhoNameTheGods.Models.God", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<int>("Favor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gods");
                });

            modelBuilder.Entity("TheyWhoNameTheGods.Models.Creation", b =>
                {
                    b.HasOne("TheyWhoNameTheGods.Models.God", null)
                        .WithMany("DivineCreations")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
